/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as PitchRouteImport } from './routes/pitch'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedAmWalkthroughRouteImport } from './routes/_authed/am-walkthrough'
import { Route as AuthedArchitectureRouteImport } from './routes/_authed/architecture'
import { Route as AuthedCategoriesRouteImport } from './routes/_authed/categories'
import { Route as AuthedCollectionsRouteImport } from './routes/_authed/collections'
import { Route as AuthedConfigRouteImport } from './routes/_authed/config'
import { Route as AuthedDataReviewRouteImport } from './routes/_authed/data-review'
import { Route as AuthedLogicRouteImport } from './routes/_authed/logic'
import { Route as AuthedPlaybookRouteImport } from './routes/_authed/playbook'
import { Route as AuthedSsotSpecRouteImport } from './routes/_authed/ssot-spec'
import { Route as AuthedStockRouteImport } from './routes/_authed/stock'
import { Route as AuthedSuppliersRouteImport } from './routes/_authed/suppliers'
import { Route as AuthedTechStackRouteImport } from './routes/_authed/tech-stack'
import { Route as AuthedAdminAuditRouteImport } from './routes/_authed/admin/audit'
import { Route as AuthedAdminReportRouteImport } from './routes/_authed/admin/report'
import { Route as AuthedAdminUsersRouteImport } from './routes/_authed/admin/users'
import { Route as AuthedCataloguesIndexRouteImport } from './routes/_authed/catalogues/index'
import { Route as AuthedClientsGuideRouteImport } from './routes/_authed/clients/guide'
import { Route as AuthedCataloguesReparseIndexRouteImport } from './routes/_authed/catalogues/reparse/index'
import { Route as AuthedCataloguesReparseBatchIdRouteImport } from './routes/_authed/catalogues/reparse/$batchId'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PitchRoute = PitchRouteImport.update({
  id: '/pitch',
  path: '/pitch',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAmWalkthroughRoute = AuthedAmWalkthroughRouteImport.update({
  id: '/am-walkthrough',
  path: '/am-walkthrough',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedArchitectureRoute = AuthedArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCategoriesRoute = AuthedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCollectionsRoute = AuthedCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedConfigRoute = AuthedConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDataReviewRoute = AuthedDataReviewRouteImport.update({
  id: '/data-review',
  path: '/data-review',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLogicRoute = AuthedLogicRouteImport.update({
  id: '/logic',
  path: '/logic',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPlaybookRoute = AuthedPlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSsotSpecRoute = AuthedSsotSpecRouteImport.update({
  id: '/ssot-spec',
  path: '/ssot-spec',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStockRoute = AuthedStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSuppliersRoute = AuthedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTechStackRoute = AuthedTechStackRouteImport.update({
  id: '/tech-stack',
  path: '/tech-stack',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminAuditRoute = AuthedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminReportRoute = AuthedAdminReportRouteImport.update({
  id: '/admin/report',
  path: '/admin/report',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminUsersRoute = AuthedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCataloguesIndexRoute = AuthedCataloguesIndexRouteImport.update({
  id: '/catalogues/',
  path: '/catalogues/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedClientsGuideRoute = AuthedClientsGuideRouteImport.update({
  id: '/clients/guide',
  path: '/clients/guide',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCataloguesReparseIndexRoute =
  AuthedCataloguesReparseIndexRouteImport.update({
    id: '/catalogues/reparse/',
    path: '/catalogues/reparse/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedCataloguesReparseBatchIdRoute =
  AuthedCataloguesReparseBatchIdRouteImport.update({
    id: '/catalogues/reparse/$batchId',
    path: '/catalogues/reparse/$batchId',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/pitch': typeof PitchRoute
  '/pricing': typeof PricingRoute
  '/am-walkthrough': typeof AuthedAmWalkthroughRoute
  '/architecture': typeof AuthedArchitectureRoute
  '/categories': typeof AuthedCategoriesRoute
  '/collections': typeof AuthedCollectionsRoute
  '/config': typeof AuthedConfigRoute
  '/data-review': typeof AuthedDataReviewRoute
  '/logic': typeof AuthedLogicRoute
  '/playbook': typeof AuthedPlaybookRoute
  '/ssot-spec': typeof AuthedSsotSpecRoute
  '/stock': typeof AuthedStockRoute
  '/suppliers': typeof AuthedSuppliersRoute
  '/tech-stack': typeof AuthedTechStackRoute
  '/admin/audit': typeof AuthedAdminAuditRoute
  '/admin/report': typeof AuthedAdminReportRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/clients/guide': typeof AuthedClientsGuideRoute
  '/catalogues/': typeof AuthedCataloguesIndexRoute
  '/catalogues/reparse/$batchId': typeof AuthedCataloguesReparseBatchIdRoute
  '/catalogues/reparse/': typeof AuthedCataloguesReparseIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/pitch': typeof PitchRoute
  '/pricing': typeof PricingRoute
  '/am-walkthrough': typeof AuthedAmWalkthroughRoute
  '/architecture': typeof AuthedArchitectureRoute
  '/categories': typeof AuthedCategoriesRoute
  '/collections': typeof AuthedCollectionsRoute
  '/config': typeof AuthedConfigRoute
  '/data-review': typeof AuthedDataReviewRoute
  '/logic': typeof AuthedLogicRoute
  '/playbook': typeof AuthedPlaybookRoute
  '/ssot-spec': typeof AuthedSsotSpecRoute
  '/stock': typeof AuthedStockRoute
  '/suppliers': typeof AuthedSuppliersRoute
  '/tech-stack': typeof AuthedTechStackRoute
  '/': typeof AuthedIndexRoute
  '/admin/audit': typeof AuthedAdminAuditRoute
  '/admin/report': typeof AuthedAdminReportRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/clients/guide': typeof AuthedClientsGuideRoute
  '/catalogues': typeof AuthedCataloguesIndexRoute
  '/catalogues/reparse/$batchId': typeof AuthedCataloguesReparseBatchIdRoute
  '/catalogues/reparse': typeof AuthedCataloguesReparseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/pitch': typeof PitchRoute
  '/pricing': typeof PricingRoute
  '/_authed/am-walkthrough': typeof AuthedAmWalkthroughRoute
  '/_authed/architecture': typeof AuthedArchitectureRoute
  '/_authed/categories': typeof AuthedCategoriesRoute
  '/_authed/collections': typeof AuthedCollectionsRoute
  '/_authed/config': typeof AuthedConfigRoute
  '/_authed/data-review': typeof AuthedDataReviewRoute
  '/_authed/logic': typeof AuthedLogicRoute
  '/_authed/playbook': typeof AuthedPlaybookRoute
  '/_authed/ssot-spec': typeof AuthedSsotSpecRoute
  '/_authed/stock': typeof AuthedStockRoute
  '/_authed/suppliers': typeof AuthedSuppliersRoute
  '/_authed/tech-stack': typeof AuthedTechStackRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/admin/audit': typeof AuthedAdminAuditRoute
  '/_authed/admin/report': typeof AuthedAdminReportRoute
  '/_authed/admin/users': typeof AuthedAdminUsersRoute
  '/_authed/clients/guide': typeof AuthedClientsGuideRoute
  '/_authed/catalogues/': typeof AuthedCataloguesIndexRoute
  '/_authed/catalogues/reparse/$batchId': typeof AuthedCataloguesReparseBatchIdRoute
  '/_authed/catalogues/reparse/': typeof AuthedCataloguesReparseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboard'
    | '/pitch'
    | '/pricing'
    | '/am-walkthrough'
    | '/architecture'
    | '/categories'
    | '/collections'
    | '/config'
    | '/data-review'
    | '/logic'
    | '/playbook'
    | '/ssot-spec'
    | '/stock'
    | '/suppliers'
    | '/tech-stack'
    | '/admin/audit'
    | '/admin/report'
    | '/admin/users'
    | '/clients/guide'
    | '/catalogues/'
    | '/catalogues/reparse/$batchId'
    | '/catalogues/reparse/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/onboard'
    | '/pitch'
    | '/pricing'
    | '/am-walkthrough'
    | '/architecture'
    | '/categories'
    | '/collections'
    | '/config'
    | '/data-review'
    | '/logic'
    | '/playbook'
    | '/ssot-spec'
    | '/stock'
    | '/suppliers'
    | '/tech-stack'
    | '/'
    | '/admin/audit'
    | '/admin/report'
    | '/admin/users'
    | '/clients/guide'
    | '/catalogues'
    | '/catalogues/reparse/$batchId'
    | '/catalogues/reparse'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/onboard'
    | '/pitch'
    | '/pricing'
    | '/_authed/am-walkthrough'
    | '/_authed/architecture'
    | '/_authed/categories'
    | '/_authed/collections'
    | '/_authed/config'
    | '/_authed/data-review'
    | '/_authed/logic'
    | '/_authed/playbook'
    | '/_authed/ssot-spec'
    | '/_authed/stock'
    | '/_authed/suppliers'
    | '/_authed/tech-stack'
    | '/_authed/'
    | '/_authed/admin/audit'
    | '/_authed/admin/report'
    | '/_authed/admin/users'
    | '/_authed/clients/guide'
    | '/_authed/catalogues/'
    | '/_authed/catalogues/reparse/$batchId'
    | '/_authed/catalogues/reparse/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardRoute: typeof OnboardRoute
  PitchRoute: typeof PitchRoute
  PricingRoute: typeof PricingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pitch': {
      id: '/pitch'
      path: '/pitch'
      fullPath: '/pitch'
      preLoaderRoute: typeof PitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/am-walkthrough': {
      id: '/_authed/am-walkthrough'
      path: '/am-walkthrough'
      fullPath: '/am-walkthrough'
      preLoaderRoute: typeof AuthedAmWalkthroughRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/architecture': {
      id: '/_authed/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof AuthedArchitectureRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/categories': {
      id: '/_authed/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthedCategoriesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/collections': {
      id: '/_authed/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AuthedCollectionsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/config': {
      id: '/_authed/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof AuthedConfigRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/data-review': {
      id: '/_authed/data-review'
      path: '/data-review'
      fullPath: '/data-review'
      preLoaderRoute: typeof AuthedDataReviewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/logic': {
      id: '/_authed/logic'
      path: '/logic'
      fullPath: '/logic'
      preLoaderRoute: typeof AuthedLogicRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/playbook': {
      id: '/_authed/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof AuthedPlaybookRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ssot-spec': {
      id: '/_authed/ssot-spec'
      path: '/ssot-spec'
      fullPath: '/ssot-spec'
      preLoaderRoute: typeof AuthedSsotSpecRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/stock': {
      id: '/_authed/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AuthedStockRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/suppliers': {
      id: '/_authed/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthedSuppliersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tech-stack': {
      id: '/_authed/tech-stack'
      path: '/tech-stack'
      fullPath: '/tech-stack'
      preLoaderRoute: typeof AuthedTechStackRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/audit': {
      id: '/_authed/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthedAdminAuditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/report': {
      id: '/_authed/admin/report'
      path: '/admin/report'
      fullPath: '/admin/report'
      preLoaderRoute: typeof AuthedAdminReportRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/users': {
      id: '/_authed/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthedAdminUsersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/catalogues/': {
      id: '/_authed/catalogues/'
      path: '/catalogues'
      fullPath: '/catalogues/'
      preLoaderRoute: typeof AuthedCataloguesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/clients/guide': {
      id: '/_authed/clients/guide'
      path: '/clients/guide'
      fullPath: '/clients/guide'
      preLoaderRoute: typeof AuthedClientsGuideRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/catalogues/reparse/': {
      id: '/_authed/catalogues/reparse/'
      path: '/catalogues/reparse'
      fullPath: '/catalogues/reparse/'
      preLoaderRoute: typeof AuthedCataloguesReparseIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/catalogues/reparse/$batchId': {
      id: '/_authed/catalogues/reparse/$batchId'
      path: '/catalogues/reparse/$batchId'
      fullPath: '/catalogues/reparse/$batchId'
      preLoaderRoute: typeof AuthedCataloguesReparseBatchIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAmWalkthroughRoute: typeof AuthedAmWalkthroughRoute
  AuthedArchitectureRoute: typeof AuthedArchitectureRoute
  AuthedCategoriesRoute: typeof AuthedCategoriesRoute
  AuthedCollectionsRoute: typeof AuthedCollectionsRoute
  AuthedConfigRoute: typeof AuthedConfigRoute
  AuthedDataReviewRoute: typeof AuthedDataReviewRoute
  AuthedLogicRoute: typeof AuthedLogicRoute
  AuthedPlaybookRoute: typeof AuthedPlaybookRoute
  AuthedSsotSpecRoute: typeof AuthedSsotSpecRoute
  AuthedStockRoute: typeof AuthedStockRoute
  AuthedSuppliersRoute: typeof AuthedSuppliersRoute
  AuthedTechStackRoute: typeof AuthedTechStackRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedAdminAuditRoute: typeof AuthedAdminAuditRoute
  AuthedAdminReportRoute: typeof AuthedAdminReportRoute
  AuthedAdminUsersRoute: typeof AuthedAdminUsersRoute
  AuthedClientsGuideRoute: typeof AuthedClientsGuideRoute
  AuthedCataloguesIndexRoute: typeof AuthedCataloguesIndexRoute
  AuthedCataloguesReparseBatchIdRoute: typeof AuthedCataloguesReparseBatchIdRoute
  AuthedCataloguesReparseIndexRoute: typeof AuthedCataloguesReparseIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAmWalkthroughRoute: AuthedAmWalkthroughRoute,
  AuthedArchitectureRoute: AuthedArchitectureRoute,
  AuthedCategoriesRoute: AuthedCategoriesRoute,
  AuthedCollectionsRoute: AuthedCollectionsRoute,
  AuthedConfigRoute: AuthedConfigRoute,
  AuthedDataReviewRoute: AuthedDataReviewRoute,
  AuthedLogicRoute: AuthedLogicRoute,
  AuthedPlaybookRoute: AuthedPlaybookRoute,
  AuthedSsotSpecRoute: AuthedSsotSpecRoute,
  AuthedStockRoute: AuthedStockRoute,
  AuthedSuppliersRoute: AuthedSuppliersRoute,
  AuthedTechStackRoute: AuthedTechStackRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedAdminAuditRoute: AuthedAdminAuditRoute,
  AuthedAdminReportRoute: AuthedAdminReportRoute,
  AuthedAdminUsersRoute: AuthedAdminUsersRoute,
  AuthedClientsGuideRoute: AuthedClientsGuideRoute,
  AuthedCataloguesIndexRoute: AuthedCataloguesIndexRoute,
  AuthedCataloguesReparseBatchIdRoute: AuthedCataloguesReparseBatchIdRoute,
  AuthedCataloguesReparseIndexRoute: AuthedCataloguesReparseIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardRoute: OnboardRoute,
  PitchRoute: PitchRoute,
  PricingRoute: PricingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
