"""Registered supplier-source contract declarations."""

from .alfamedic import ALFAMEDIC_PRICE_LIST_V1
from .hills import HILLS_PRICE_LIST_V1
from .kangaroo import (
    KANGAROO_EARTHZ_PET_PRICE_SHEET_V1,
    KANGAROO_MIXED_PRICE_CATALOGUE_V1,
    KANGAROO_PURINA_PROPLAN_VETERINARY_DIETS_V1,
)
from .vetapet import VETAPET_NON_VET_PRICE_LIST_V1, VETAPET_VET_PRICE_LIST_V1

__all__ = [
    "ALFAMEDIC_PRICE_LIST_V1",
    "HILLS_PRICE_LIST_V1",
    "KANGAROO_EARTHZ_PET_PRICE_SHEET_V1",
    "KANGAROO_MIXED_PRICE_CATALOGUE_V1",
    "KANGAROO_PURINA_PROPLAN_VETERINARY_DIETS_V1",
    "VETAPET_NON_VET_PRICE_LIST_V1",
    "VETAPET_VET_PRICE_LIST_V1",
]
