"""Registered supplier-source contract declarations."""

from .asia_vet_medical import ASIA_VET_MEDICAL_VETRISCIENCE_PRICE_LIST_V1
from .alfamedic import ALFAMEDIC_PRICE_LIST_V1
from .idexx import IDEXX_ORDER_PORTAL_SNAPSHOT_V1
from .hills import HILLS_PRICE_LIST_V1
from .kangaroo import (
    KANGAROO_EARTHZ_PET_PRICE_SHEET_V1,
    KANGAROO_MIXED_PRICE_CATALOGUE_V1,
    KANGAROO_PURINA_PROPLAN_VETERINARY_DIETS_V1,
)
from .kangaroo_pet_nutrition import (
    KANGAROO_PET_NUTRITION_CATALOGUE_BUNDLE_V1,
    KANGAROO_PET_NUTRITION_UNIT_PRICE_LIST_V1,
)
from .kpn_trading import (
    KPN_TRADING_CASE_ONLY_PRICE_LIST_V1,
    KPN_TRADING_CATALOGUE_BUNDLE_V1,
    KPN_TRADING_PACK_PRICE_LIST_V1,
)
from .queens_pharma import QUEENS_PHARMA_ZOETIS_PRICE_LIST_V1
from .royal_canin import (
    ROYAL_CANIN_NON_VET_WEBSHOP_SNAPSHOT_V1,
    ROYAL_CANIN_VET_WEBSHOP_SNAPSHOT_V1,
)
from .vetapet import VETAPET_NON_VET_PRICE_LIST_V1, VETAPET_VET_PRICE_LIST_V1

__all__ = [
    "QUEENS_PHARMA_ZOETIS_PRICE_LIST_V1",
    "IDEXX_ORDER_PORTAL_SNAPSHOT_V1",
    "ASIA_VET_MEDICAL_VETRISCIENCE_PRICE_LIST_V1",
    "ROYAL_CANIN_NON_VET_WEBSHOP_SNAPSHOT_V1",
    "ROYAL_CANIN_VET_WEBSHOP_SNAPSHOT_V1",
    "ALFAMEDIC_PRICE_LIST_V1",
    "HILLS_PRICE_LIST_V1",
    "KANGAROO_EARTHZ_PET_PRICE_SHEET_V1",
    "KANGAROO_MIXED_PRICE_CATALOGUE_V1",
    "KANGAROO_PET_NUTRITION_CATALOGUE_BUNDLE_V1",
    "KANGAROO_PET_NUTRITION_UNIT_PRICE_LIST_V1",
    "KANGAROO_PURINA_PROPLAN_VETERINARY_DIETS_V1",
    "KPN_TRADING_CASE_ONLY_PRICE_LIST_V1",
    "KPN_TRADING_CATALOGUE_BUNDLE_V1",
    "KPN_TRADING_PACK_PRICE_LIST_V1",
    "VETAPET_NON_VET_PRICE_LIST_V1",
    "VETAPET_VET_PRICE_LIST_V1",
]
